# Generated by Django 4.2.14 on 2024-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axoli',
            name='lastname',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='axoli',
            name='phone',
            field=models.CharField(default='main', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='axoli',
            name='status',
            field=models.CharField(default='main', max_length=225),
            preserve_default=False,
        ),
    ]
