# Generated by Django 4.2.14 on 2024-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_axoli_lastname_axoli_phone_axoli_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='axoli',
            name='discreption',
            field=models.TextField(default='main'),
            preserve_default=False,
        ),
    ]
