# Generated by Django 5.0 on 2024-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_axoli_discreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='axoli',
            name='passport',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
