# Generated by Django 5.0 on 2024-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_axoli_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='axoli',
            name='birth',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
