# Generated by Django 5.0 on 2024-10-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_axoli_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='axoli',
            name='role',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='axoli',
            name='status',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
