# Generated by Django 5.0 on 2024-10-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_axoli_role_alter_axoli_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axoli',
            name='status',
            field=models.BooleanField(),
        ),
    ]
