# Generated by Django 5.0 on 2024-10-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_axoli_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axoli',
            name='status',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
