# Generated by Django 5.0 on 2024-10-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_axoli_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=225)),
                ('status', models.CharField(blank=True, max_length=225)),
                ('passport', models.CharField(max_length=255)),
                ('birth', models.CharField(max_length=255)),
            ],
        ),
    ]
